Update to discord.js v14
whirlxd/Musico pull request #14
Opened 2022-09-20 07:02 UTC by jmiln

This updates stuff to be discord.js v14 compatible, which was needed in order to update discord-player, which in turn was needed to make Spotify links work again apparently.

- This probably did screw up some indenting, my environment is set for 4 spaces instead of tabs (Whoops)

2022-09-25 13:48 UTC, Whirl21 commented
Jesus 
Thanks homie , ill take a look over it next week and either merge it or sideline the v 13 branch and make this the main branch

2022-09-25 19:06 UTC, jmiln commented
Sounds good. Thanks for the solid bot. This was the first music bot I've really worked with, and it's all nicely laid out and easy to make sense of

2022-09-30 12:46 UTC, Whirl21 commented
aight i got sick for a few days so couldn't review it , will do so

2022-10-04 18:41 UTC, dotxyzcf requested changes
In files:

commands\context-menus\message\add.js
commands\slash\music\autoplay.js
commands\slash\music\play.js
commands\slash\music\repeat.js

<img width="468" alt="image" src="https://user-images.githubusercontent.com/92203938/193898956-e3856692-d13f-4c9d-8c69-ae1755c8335a.png">

there are "discord--player" which makes the bot crashing. please change it to "discord-player", otherwise the bot dont start:

`D:\Documents\Testing\Musico-musico>npm run musico

> musico@3.0.1 musico
> node musico.js

node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'discord--player'
Require stack:
- D:\Documents\Testing\Musico-musico\commands\context-menus\message\add.js
- D:\Documents\Testing\Musico-musico\handlers\interactionHandlers.js
- D:\Documents\Testing\Musico-musico\musico.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Documents\Testing\Musico-musico\commands\context-menus\message\add.js:1:23)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Documents\\Testing\\Musico-musico\\commands\\context-menus\\message\\add.js',
    'D:\\Documents\\Testing\\Musico-musico\\handlers\\interactionHandlers.js',
    'D:\\Documents\\Testing\\Musico-musico\\musico.js'
  ]
}

D:\Documents\Testing\Musico-musico>npm run musico

> musico@3.0.1 musico
> node musico.js

[Musico] | Logged in as Musicio#3682!
[Musico] | Servers! ["0"]
[Musico] | Users! ["1"]
[Musico] | Channels! ["0"]
[Musico] | Loaded all (/) undefined commands

D:\Documents\Testing\Musico-musico>`

2022-10-04 18:45 UTC, virtualized-human requested changes

2022-10-04 18:45 UTC, dotxyzcf commented on commands/context-menus/message/add.js
> +const { QueryType } = require("discord--player");
Change from "discord--player" to "discord-player"

2022-10-04 18:45 UTC, dotxyzcf commented on commands/slash/music/autoplay.js
> +const { QueueRepeatMode } = require("discord--player");
Change from "discord--player" to "discord-player"

2022-10-04 18:45 UTC, dotxyzcf commented on commands/slash/music/play.js
> +const { QueryType } = require("discord--player");
Change from "discord--player" to "discord-player"

2022-10-04 18:45 UTC, dotxyzcf commented on commands/slash/music/repeat.js
> +const { QueueRepeatMode } = require("discord--player");
Change from "discord--player" to "discord-player"

2022-10-04 21:23 UTC, jmiln commented
Those are fixed, thanks for catching those. 

I'd switched it to discord-portable-player for a while since it was basically the same but had updated to Discord.js v13 first, and I guess I only removed the portable part, forgetting a dash

2022-10-19 16:13 UTC, virtualized-human commented
@Whirl21 dont forget it!

2022-11-04 15:00 UTC, Whirl21 approved these changes
aights

2022-11-04 15:01 UTC, merged